// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AutomateOrder.proto

package grpc.automateorder.smartwarehouse;

public final class AutomateOrderServiceImpl {
  private AutomateOrderServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_Confirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_Confirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_OrderStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_OrderStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023AutomateOrder.proto\022\016smartwarehouse\"J\n" +
      "\014OrderRequest\022\021\n\titem_name\030\001 \001(\t\022\020\n\010quan" +
      "tity\030\002 \001(\005\022\025\n\rcustomer_name\030\003 \001(\t\"\037\n\014Con" +
      "firmation\022\017\n\007message\030\001 \001(\t\"\036\n\013OrderStatu" +
      "s\022\017\n\007message\030\001 \001(\t2\367\001\n\024AutomateOrderServ" +
      "ice\022I\n\tMakeOrder\022\034.smartwarehouse.OrderR" +
      "equest\032\034.smartwarehouse.Confirmation\"\000\022I" +
      "\n\tStopOrder\022\034.smartwarehouse.OrderReques" +
      "t\032\034.smartwarehouse.Confirmation\"\000\022I\n\006Sta" +
      "tus\022\034.smartwarehouse.OrderRequest\032\033.smar" +
      "twarehouse.OrderStatus\"\000(\0010\001B?\n!grpc.aut" +
      "omateorder.smartwarehouseB\030AutomateOrder" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartwarehouse_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartwarehouse_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_OrderRequest_descriptor,
        new java.lang.String[] { "ItemName", "Quantity", "CustomerName", });
    internal_static_smartwarehouse_Confirmation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartwarehouse_Confirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_Confirmation_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_smartwarehouse_OrderStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartwarehouse_OrderStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_OrderStatus_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
