// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AutomateOrder.proto

package grpc.automateorder.smartwarehouse;

public interface OrderStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.OrderStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
