// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package grpc.smartlighting.smartwarehouse;

public interface BrightnessLevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.BrightnessLevel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float level = 1;</code>
   */
  float getLevel();
}
