// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package grpc.smartlighting.smartwarehouse;

public interface ConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.Confirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
