// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package grpc.smartlighting.smartwarehouse;

public interface LightStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.LightStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool on = 1;</code>
   */
  boolean getOn();
}
