// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package grpc.smartlighting.smartwarehouse;

public final class MathServiceImpl {
  private MathServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_BrightnessLevel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_BrightnessLevel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_OccupancyStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_OccupancyStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_RemoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_RemoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_LightStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_LightStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_Confirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_Confirmation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SmartLighting.proto\022\016smartwarehouse\" \n" +
      "\017BrightnessLevel\022\r\n\005level\030\001 \001(\002\"#\n\017Occup" +
      "ancyStatus\022\020\n\010occupied\030\001 \001(\010\"\033\n\rRemoteRe" +
      "quest\022\n\n\002on\030\001 \001(\010\"\031\n\013LightStatus\022\n\n\002on\030\001" +
      " \001(\010\"\037\n\014Confirmation\022\017\n\007message\030\001 \001(\t2\373\001" +
      "\n\024SmartLightingService\022N\n\nBrightness\022\037.s" +
      "martwarehouse.BrightnessLevel\032\033.smartwar" +
      "ehouse.LightStatus\"\000(\001\022J\n\006Switch\022\037.smart" +
      "warehouse.OccupancyStatus\032\033.smartwarehou" +
      "se.LightStatus\"\000(\001\022G\n\006Remote\022\035.smartware" +
      "house.RemoteRequest\032\034.smartwarehouse.Con" +
      "firmation\"\000B6\n!grpc.smartlighting.smartw" +
      "arehouseB\017MathServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartwarehouse_BrightnessLevel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartwarehouse_BrightnessLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_BrightnessLevel_descriptor,
        new java.lang.String[] { "Level", });
    internal_static_smartwarehouse_OccupancyStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartwarehouse_OccupancyStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_OccupancyStatus_descriptor,
        new java.lang.String[] { "Occupied", });
    internal_static_smartwarehouse_RemoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartwarehouse_RemoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_RemoteRequest_descriptor,
        new java.lang.String[] { "On", });
    internal_static_smartwarehouse_LightStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartwarehouse_LightStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_LightStatus_descriptor,
        new java.lang.String[] { "On", });
    internal_static_smartwarehouse_Confirmation_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smartwarehouse_Confirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_Confirmation_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
