// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package grpc.smartlighting.smartwarehouse;

public interface OccupancyStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.OccupancyStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool occupied = 1;</code>
   */
  boolean getOccupied();
}
