// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrackStock.proto

package grpc.trackstock.smartwarehouse;

public final class TrackStockServiceImpl {
  private TrackStockServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_StockItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_StockItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_Confirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_Confirmation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TrackStock.proto\022\016smartwarehouse\"+\n\tSt" +
      "ockItem\022\014\n\004name\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\"" +
      "!\n\013ListRequest\022\022\n\nlist_items\030\001 \001(\005\"0\n\014Co" +
      "nfirmation\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002" +
      " \001(\t2\336\001\n\021TrackStockService\022@\n\003Add\022\031.smar" +
      "twarehouse.StockItem\032\034.smartwarehouse.Co" +
      "nfirmation\"\000\022C\n\006Remove\022\031.smartwarehouse." +
      "StockItem\032\034.smartwarehouse.Confirmation\"" +
      "\000\022B\n\004List\022\033.smartwarehouse.ListRequest\032\031" +
      ".smartwarehouse.StockItem\"\0000\001B9\n\036grpc.tr" +
      "ackstock.smartwarehouseB\025TrackStockServi" +
      "ceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartwarehouse_StockItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartwarehouse_StockItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_StockItem_descriptor,
        new java.lang.String[] { "Name", "Quantity", });
    internal_static_smartwarehouse_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartwarehouse_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_ListRequest_descriptor,
        new java.lang.String[] { "ListItems", });
    internal_static_smartwarehouse_Confirmation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartwarehouse_Confirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_Confirmation_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
