// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrackStock.proto

package smartwarehouse;

public interface ConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.Confirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
