// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrackStock.proto

package smartwarehouse;

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.ListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * int32 max_items = 1;
   * </pre>
   *
   * <code>int32 list_items = 1;</code>
   */
  int getListItems();
}
