// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrackStock.proto

package smartwarehouse;

public interface StockItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.StockItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * float price = 3;
   * </pre>
   *
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();
}
